USE		MoH
GO

PRINT 'Labs Start'
BULK INSERT Labs FROM 'I:\PDH\MoH\ADMISSIONS.csv' WITH (FIRSTROW = 2, ROWTERMINATOR = '0x0a', KILOBYTES_PER_BATCH = 16384, FIELDTERMINATOR = '|'); 
PRINT 'Labs End'



--PRINT 'ADMISSIONS Start'
--BULK INSERT ADMISSIONS FROM 'f:\PDH\MIMICIII\ADMISSIONS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a'); 
--PRINT 'ADMISSIONS End'
--PRINT 'CALLOUT Start'
--BULK INSERT CALLOUT FROM 'f:\PDH\MIMICIII\CALLOUT.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'CALLOUT End'
--PRINT 'CAREGIVERS Start'
--BULK INSERT CAREGIVERS FROM 'f:\PDH\MIMICIII\CAREGIVERS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'CAREGIVERS End'
--PRINT ''
--PRINT '*** CHARTEVENTS See Below ***'
--PRINT ''
--PRINT 'CPTEVENTS Start'
--BULK INSERT CPTEVENTS FROM 'f:\PDH\MIMICIII\CPTEVENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'CPTEVENTS End'
--PRINT 'D_CPT Start'
--BULK INSERT D_CPT FROM 'f:\PDH\MIMICIII\D_CPT.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'D_CPT End'
--PRINT 'D_ICD_DIAGNOSES Start'
--BULK INSERT D_ICD_DIAGNOSES FROM 'f:\PDH\MIMICIII\D_ICD_DIAGNOSES.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'D_ICD_DIAGNOSES End'
--PRINT 'D_ICD_PROCEDURES Start'
--BULK INSERT D_ICD_PROCEDURES FROM 'f:\PDH\MIMICIII\D_ICD_PROCEDURES.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'D_ICD_PROCEDURES End'
--PRINT 'D_ITEMS Start'
--BULK INSERT D_ITEMS FROM 'f:\PDH\MIMICIII\D_ITEMS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'D_ITEMS End'
--PRINT 'D_LABITEMS Start'
--BULK INSERT D_LABITEMS FROM 'f:\PDH\MIMICIII\D_LABITEMS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'D_LABITEMS End'
--PRINT 'DATETIMEEVENTS Start'
--BULK INSERT DATETIMEEVENTS FROM 'f:\PDH\MIMICIII\DATETIMEEVENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'DATETIMEEVENTS End'
--PRINT 'DIAGNOSES_ICD Start'
--BULK INSERT DIAGNOSES_ICD FROM 'f:\PDH\MIMICIII\DIAGNOSES_ICD.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'DIAGNOSES_ICD End'
--PRINT 'DRGCODES Start'
--BULK INSERT DRGCODES FROM 'f:\PDH\MIMICIII\DRGCODES.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'DRGCODES End'
--PRINT 'ICUSTAYS Start'
--BULK INSERT ICUSTAYS FROM 'f:\PDH\MIMICIII\ICUSTAYS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'ICUSTAYS End'
--PRINT 'INPUTEVENTS_CV Start'
--BULK INSERT INPUTEVENTS_CV FROM 'f:\PDH\MIMICIII\INPUTEVENTS_CV.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'INPUTEVENTS_CV End'
--PRINT 'INPUTEVENTS_MV Start'
--BULK INSERT INPUTEVENTS_MV FROM 'f:\PDH\MIMICIII\INPUTEVENTS_MV.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'INPUTEVENTS_MV End'
--PRINT 'LABEVENTS Start'
--BULK INSERT LABEVENTS FROM 'f:\PDH\MIMICIII\LABEVENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'LABEVENTS End'
--PRINT 'MICROBIOLOGYEVENTS Start'
--BULK INSERT MICROBIOLOGYEVENTS FROM 'f:\PDH\MIMICIII\MICROBIOLOGYEVENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'MICROBIOLOGYEVENTS End'
--PRINT 'NOTEEVENTS Start'
--BULK INSERT NOTEEVENTS FROM 'f:\PDH\MIMICIII\NOTEEVENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'NOTEEVENTS End'
--PRINT 'OUTPUTEVENTS Start'
--BULK INSERT OUTPUTEVENTS FROM 'f:\PDH\MIMICIII\OUTPUTEVENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'OUTPUTEVENTS End'
--PRINT 'PATIENTS Start'
--BULK INSERT PATIENTS FROM 'f:\PDH\MIMICIII\PATIENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'PATIENTS End'
--PRINT 'PRESCRIPTIONS Start'
--BULK INSERT PRESCRIPTIONS FROM 'f:\PDH\MIMICIII\PRESCRIPTIONS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'PRESCRIPTIONS End'
--PRINT 'PROCEDUREEVENTS_MV Start'
--BULK INSERT PROCEDUREEVENTS_MV FROM 'f:\PDH\MIMICIII\PROCEDUREEVENTS_MV.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'PROCEDUREEVENTS_MV End'
--PRINT 'PROCEDURES_ICD Start'
--BULK INSERT PROCEDURES_ICD FROM 'f:\PDH\MIMICIII\PROCEDURES_ICD.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'PROCEDURES_ICD End'
--PRINT 'SERVICES Start'
--BULK INSERT [SERVICES] FROM 'f:\PDH\MIMICIII\SERVICES.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'SERVICES End'
--PRINT 'TRANSFERS Start'
--BULK INSERT TRANSFERS FROM 'f:\PDH\MIMICIII\TRANSFERS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a');
--PRINT 'TRANSFERS End'
--GO

---------------------------------------------------------------------------------------------------------------------------
---- Chartevents table is done separately because it is a lot bigger and causes issues :) (34GB, 330M events)

---- First drop the primary key constraint
---- Import the data using a batch size of 1000
---- Add the clustered primary key constraint on again

---- IT IS ESSENTIAL THAT YOUR MIMIC DATABASE IS IN SIMPLE RECOVERY MODE DURING THE IMPORT AT LEAST.

---------------------------------------------------------------------------------------------------------------------------

--ALTER TABLE [dbo].[CHARTEVENTS] DROP CONSTRAINT [chartevents_rowid_pk] WITH ( ONLINE = OFF )
--GO

--PRINT 'CHARTEVENTS Start'
--BULK INSERT CHARTEVENTS FROM 'f:\PDH\MIMICIII\CHARTEVENTS.csv' WITH (FIRSTROW = 2, FORMAT = 'CSV', ROWTERMINATOR = '0x0a', BATCHSIZE = 100000);
--PRINT 'CHARTEVENTS End'
--GO

--ALTER TABLE [dbo].[CHARTEVENTS] ADD  CONSTRAINT [chartevents_rowid_pk] PRIMARY KEY CLUSTERED 
--(
--	[ROW_ID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO